---
title: "Introducción a R"
format:
  html:
    code-copy: true
---

# Lenguajes de programación de código libre

## R y RStudio

### Características

-   R es un lenguaje interpretado, lo que significa que los usuarios acceden a sus funciones a través de un intérprete de línea de comandos

-   A diferencia de Python y Java, R es un lenguaje de programación específico de dominio (diseñado para un campo en especial, en este caso orientado al cálculo estadístico y generación de gráficos)

-   Es un software libre, lo que significa que no tiene costo en su descarga, uso y distribución e incluso modificación

-   R es competencia de Excel, Phyton, SPSS y STATA

-   Se parece a Matlab y su sintaxis recuerda a C / C++

-   R fue desarrollado inicialmente por Ross Ihaka y Robert Gentleman en 1995 dentro de la Universidad de Auckland, Nueva Zelanda, y se encuentra en desarrollo constante por el R Development Core Team

-   La versión beta más estable fue lanzada hasta el año 2000

-   RStudio es un entorno de desarrollo integrado (IDE) para R

### Ventajas y desventajas de R

-   Es un software libre

-   No hay responsabilidad en caso de errores en el código

-   Es uno de los primeros lenguajes en recibir los nuevos temas

-   Tiene una fácil conectividad y compatibilidad con otros lenguajes de programación

-   No tiene límite (teórico) en la lectura de bases de datos

-   Suele volverse más lento el análisis con grandes bases de datos

# Interfases y ambientes colaborativos

## Correr en R o RStudio

Las ventajas de RStudio en comparación con R son principalmente que se tiene un ambiente integrado, en donde se marcan los errores y que las diferentes ventanas permiten tener un horizonte completo del estado de la simulación.

Para instalar R y RStudio se siguen los siguientes pasos:

-   Primero se debe instalar R

-   Dependiendo de las características del sistema operativo, se puede encontrar en https://www.r-project.org/ el archivo de instalación adecuado

-   Después de elegir el idioma, acepte los términos

-   Al final de la instalación busque la carpeta en donde se guardó (generalmente *Aplicaciones*) para inicarlo

-   Para facilitar el proceso de información y bibliotecas es conveniente utilizar RStudio cuya interacción es más amigable. Es un entorno de desarrollo integrado (IDE, por sus siglas en inglés) que con la ayuda de una consola, un editor de código intuitivo, herramientas especiales de edición, visor de gráficos, entre otros, permite programar en R de una forma fácil y cómoda.

-   Se descarga RStudio en https://www.rstudio.com/, actualmente disponible en https://posit.co/, en donde se va a la pestaña \"Open Source\", de donde se puede descargar.

## Correr R en Google colab

Para usar R en Google Colab, se siguen los siguientes pasos:

-   Abre Google Colab ([https://colab.research.google.com/]{.underline})

-   Crea un nuevo notebook

-   Por defecto, Colab usa Python; para R se requieren algunos pasos adicionales b. Instalar R en el entorno de Colab En la primera celda de tu notebook, ejecuta estos comandos:

> #OJO: estos comandos se corren en Python (antes de cambiar el entorno a R)!
>
> #Se ejecuta solamente una vez
>
> !apt-get update
>
> !apt-get install -y r-base
>
> !apt-get install -y r-base-dev

-   Instalar los paquetes requeridos en R:

> !R -e \"install.packages(\'nombre_del_paquete')"

-   Usar el kernel de R (Entorno de ejecución \> Cambiar tipo de entorno de ejecución \> Seleccionar \"R")

## Ventajas de las diferentes interfaces

Las ventajas de RStudio en comparación con Google Colab son:

-   Se tiene en cada momento un registro de las variables definidos y sus valores

-   Se puede correr el código de línea en línea, o incluso partes de una línea (esto mismo se puede hacer en Colab, seleccionando la línea y picando CTRL-SHIFT-ENTER en Windows o COMMAND-SHIFT-ENTER en Mac)

Ventajas de correr en Google Colab:

-   El código desarrollado es fácilmente intercambiable con otros usuarios para trabajo colaborativo

-   No hace falta instalar R en la computadora por lo que es más flexible (por ejemplo, para uso en una tablet, para uso en clase, \...)

Desventajas de correr en Google Colab:

-   Aunque el sistema está diseñado para Python, el sistema permite trabajar en R. Sin embargo, no se puede guardar el archivo resultante en formato .R, por lo que los códigos son poco intercambiables.

-   El IDE tiene menos opciones que en RStudio

-   El sistema Markdown de colab no es el mismo que en RStudio

# Online tutorials and support

-   Manual de referencia oficial: https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf

-   [https://www.statmethods.net/index.html](https://www.google.com/url?q=https%3A%2F%2Fwww.statmethods.net%2Findex.html)

-   [https://www.coursera.org/https://rpubs.com/](https://www.google.com/url?q=https%3A%2F%2Fwww.coursera.org%2Fhttps%3A%2F%2Frpubs.com%2F)

# Primeros pasos

## Comandos basicos

Se puede encontrar información general sobre la licencia de R, indicando que es un software libre, y sobre las personas que han contribuido al lenguaje, con las siguientes instrucciones:

#Licencia de R

license()

#Contribuyentes

contributors()

#Cita

citation()

La ultima línea genera una cita en R, así como la información para generar una entrada BibTex. Si se agrega entre las paréntesis el nombre de un paquete, se genera la cita de ese paquete. Si se deja vacío el espacio, se genera la cita para el lenguaje de programación, en cuyo caso los resultados son:

## To cite R in publications use: R Core Team (2024). \_R: A Language and Environment for Statistical Computing\_. R Foundation for Statistical Computing, Vienna, Austria. \<[https://www.R-project.org/](https://www.r-project.org/)\>. A BibTeX entry for LaTeX users is \@Manual{, title = {R: A Language and Environment for Statistical Computing}, author = {{R Core Team}}, organization = {R Foundation for Statistical Computing}, address = {Vienna, Austria}, year = {2024}, url = {[https://www.R-project.org/](https://www.r-project.org/)}, } We have invested a lot of time and effort in creating R, please cite it when using it for data analysis. See also 'citation(\"pkgname\")' for citing R packages. {#to-cite-r-in-publications-use-r-core-team-2024.-_r-a-language-and-environment-for-statistical-computing_.-r-foundation-for-statistical-computing-vienna-austria.-httpswww.r-project.org.-a-bibtex-entry-for-latex-users-is-manual-title-r-a-language-and-environment-for-statistical-computing-author-r-core-team-organization-r-foundation-for-statistical-computing-address-vienna-austria-year-2024-url-httpswww.r-project.org-we-have-invested-a-lot-of-time-and-effort-in-creating-r-please-cite-it-when-using-it-for-data-analysis.-see-also-citationpkgname-for-citing-r-packages. .unnumbered}

Es importante citar adecuadamente los recursos generados en posibles publicaciones como tesis, artículos u otros trabajos.

Para encontrar ayuda con alguno de comandos, por ejemplo, la función seq, se pueden usar las siguientes instrucciones.

#Ayuda

help(seq)

help.start()

? seq

#Salir del programa

q()

# Tipos de datos

## Enteros y reales

En R, los números se manejan por defecto como "double" (reales de doble precisión); para forzar un valor a tipo entero se agrega el sufijo L. La función class() indica la clase de un objeto y typeof() su tipo interno de almacenamiento.

#Real (double) por defecto

x \<- 5

class(x)

#Entero explícito

y \<- 5L

class(y)

is.integer(y)

## Booleanos

El tipo lógico (logical) toma los valores TRUE y FALSE (o sus abreviaturas T y F). Se generan al evaluar comparaciones y se combinan con los operadores & (y), \| (o) y ! (negación); las versiones && y \|\| evalúan un solo elemento y se usan en condicionales.

a \<- TRUE

b \<- FALSE

a & b

a \| b

!a

5 \> 3

## Strings

El tipo character almacena cadenas de texto entre comillas simples o dobles. nchar() devuelve la longitud de la cadena y paste() o paste0() concatenan cadenas.

s \<- \"Operación Jupyter\"

class(s)

nchar(s)

s2 \<- paste(\"Hola\", \"mundo\")

# Declaración de variables

R no requiere declarar el tipo de una variable: el tipo se infiere del valor asignado y puede cambiar si se reasigna. El operador de asignación preferido es \<-, aunque = también funciona dentro de una instrucción; -\> asigna de izquierda a derecha. Los nombres de variables deben empezar con una letra o un punto (no seguido de número) y distinguen mayúsculas de minúsculas.

x \<- 10

x = 10

10 -\> x

mi_variable.1 \<- 3.14

# Estructuras: secuencias, decisiones y repeticiones

## Secuencias

El operador : genera una secuencia de enteros consecutivos; la función seq() permite controlar el incremento y seq_len()/seq_along() generan secuencias a partir de la longitud de un objeto.

1:10

seq(0, 1, by = 0.25)

seq_len(5)

## Estructura \"if\"

if (x \> 0) {

print(\"positivo\")

}

## Estructura \"if-else\"

if (x \> 0) {

print(\"positivo\")

} else {

print(\"no positivo\")

}

## Estructura \"for\"

for (i in 1:5) {

print(i)

}

## Estructura \"while\"

i \<- 1

while (i \<= 5) {

print(i)

i \<- i + 1

}

## Estructura \"repeat\"

repeat ejecuta el bloque indefinidamente hasta encontrar un break; es el equivalente en R de un bucle "do-while".

i \<- 1

repeat {

print(i)

i \<- i + 1

if (i \> 5) break

}

# Estructuras de datos y objetos

## Vectores

El vector es la estructura base de R: una secuencia unidimensional de elementos del mismo tipo, creada con c().

v \<- c(1, 2, 3, 4)

v\[2\]

length(v)

## Factores

Los factores representan variables categóricas; almacenan internamente enteros asociados a etiquetas (niveles).

f \<- factor(c(\"bajo\", \"alto\", \"medio\"))

levels(f)

## Matrices

Una matriz es un vector con dos dimensiones (filas y columnas), y sus elementos deben ser del mismo tipo.

m \<- matrix(1:6, nrow = 2, ncol = 3)

dim(m)

## Arreglos

array() generaliza la matriz a más de dos dimensiones.

a \<- array(1:24, dim = c(2, 3, 4))

dim(a)

## Dataframes

El data.frame es la estructura tabular estándar de R: columnas que pueden ser de distinto tipo, análoga a una hoja de cálculo.

df \<- data.frame(nombre = c(\"A\", \"B\"), valor = c(1, 2))

str(df)

## Listas

La lista es la estructura más flexible: sus elementos pueden ser de tipos y longitudes distintas, incluyendo otras listas.

lst \<- list(numero = 1, texto = \"hola\", vector = c(1,2,3))

lst\$texto

# Funciones

Las funciones se definen con function(), pueden tener argumentos con valores por defecto, y devuelven el valor de la última expresión evaluada (o el indicado con return()).

suma \<- function(a, b = 0) {

return(a + b)

}

suma(3, 4)

suma(3)

# Particularidades de cada lenguaje

## R

-   Indexado desde 1 (no desde 0).

-   Vectorizado por diseño: las operaciones aritméticas se aplican elemento a elemento sin necesidad de bucles explícitos.

-   Orientado a estadística y visualización de datos; ecosistema CRAN muy amplio para análisis estadístico.

-   Asignación con \<- como convención, aunque = es válido.

## Python

-   Indexado desde 0.

-   Lenguaje de propósito general; su uso en ciencia de datos depende de bibliotecas externas (NumPy, pandas, Matplotlib).

-   Sintaxis basada en indentación en vez de llaves para delimitar bloques.

-   Tipado dinámico, igual que R, pero con una sintaxis orientada a objetos más explícita (todo es un objeto con métodos).

## Julia

-   Indexado desde 1, como R.

-   Diseñado para desempeño numérico: se compila "just-in-time" (JIT), por lo que puede acercarse a la velocidad de C manteniendo una sintaxis de alto nivel.

-   Nació explícitamente para resolver el "problema de los dos lenguajes" (prototipar en un lenguaje interpretado y reescribir en uno compilado para producción).

-   Soporte nativo para multiple dispatch: el comportamiento de una función puede depender del tipo de todos sus argumentos, no solo del primero.

Nota: las particularidades de Julia se documentan aquí con base en las características generales del lenguaje; al no contar todavía con el notebook de Julia del proyecto, conviene revisarlas junto con el material específico cuando esté disponible.

# Conclusiones

Los tres lenguajes permiten resolver problemas similares de programación y análisis de datos, pero parten de objetivos distintos: R nació para estadística y gráficos, Python como lenguaje general que se volvió estándar en ciencia de datos gracias a sus bibliotecas, y Julia como respuesta al costo de desempeño de los otros dos en cómputo numérico intensivo. Para quien ya conoce uno de los tres, la transición a los otros es principalmente de sintaxis: la lógica de secuencias, condicionales, ciclos y funciones es la misma, y las diferencias reales aparecen en el manejo de estructuras de datos (vectorizado en R y Julia, basado en bibliotecas en Python) y en el ecosistema de cada uno.
